---
- name: Configure Hosts File
  hosts: all
  become: true
  vars:
    my_file: /etc/my_hosts
    my_template: new_hosts.j2
    #my_template: templates/hosts.j2
  tasks:
    - name: Create "{{ my_file }}" Files
      template:
        src: "{{ my_template }}"
        dest: "{{ my_file }}"
  #      owner: root
  #      group: root
  #      mode: "0644"
  #   In case hosts file needs to be collect in specific server...
  #    delegate_to: srva  
