---
- name: Task 15 - Work with Ansible Facts
  hosts: prod
  become: true
  vars:
    remote_dir: /etc/ansible/facts.d
    facts_file: files/custom.fact
  tasks:

    - name: Create the remote directory
      file:
        path: "{{ remote_dir }}"
        state: directory
        recurse: true

    - name: Install new custom facts on Prod servers
      copy:
        src: "{{ facts_file }}"
        dest: "{{ remote_dir }}"
