---
# Task 17 - Services - Set default boot target to multi-user
- name: Change default runlevel target
  hosts: test
  become: true
  tasks:

    - name: Default runlevel is multi-user target
      file:
        src:  /usr/lib/systemd/system/multi-user.target
        dest: /etc/systemd/system/default.target
        state: link
